services:
  - type: web
    name: the-gung-server
    runtime: node
    plan: free
    rootDir: apps/server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
